---
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
         submodules: recursive
         fetch-depth: 0
         persist-credentials: false
      - name: Build sourcefiles
        run: |
          HOST_UID=$(id -u)
          HOST_GID=$(id -g)
          docker run \
            -v "$(pwd):/src" \
            -e HOST_UID=${HOST_UID} \
            -e HOST_GID=${HOST_GID} \
            -u ${HOST_UID}:${HOST_GID} \
            floryn90/hugo:0.145.0-ext-alpine build -e production
      - id: "auth"
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      # - name: lighthouse
      #   uses: actions/setup-node@v3
      
      #   with:
      #     node-version: 18
      # - run: npm install && npm install -g @lhci/cli@0.14.x
      # - run: lhci autorun --collect.numberOfRuns=1 --collect.staticDirFileDiscoveryDepth=1 --collect.staticDistDir=site/public --collect.url=http://localhost/index.html

      - name: Deploy to App Engine
        id: deploy
        env:
          ACTIONS_STEP_DEBUG: true
        uses: google-github-actions/deploy-appengine@a343979004148afb93c94c712b467e8e9f01b06b # v2.1.8
        with:
          deliverables: site/app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Clean up old App Engine versions
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          
          VERSIONS=$(gcloud app versions list \
            --service default \
            --sort-by '~version.createTime' \
            --format 'value(version.id)' | tail -n +21)
          
          if [ -n "$VERSIONS" ]; then
            echo "Deleting old versions: $VERSIONS"
            for version in $VERSIONS; do
              gcloud app versions delete "$version" \
                --service default \
                --quiet || echo "Failed to delete version $version"
            done
          else
            echo "No versions to delete; 20 or fewer versions exist."
          fi
      - name: Test
        run: curl "${STEPS_DEPLOY_OUTPUTS_URL}"
        env:
          STEPS_DEPLOY_OUTPUTS_URL: ${{ steps.deploy.outputs.url }}
